@bearerToken = 

# publish event to event grid namespace topic 
POST https://evgns-workload-westeu-dev-01.westeurope-1.eventgrid.azure.net/topics/canonical1:publish?api-version=2023-11-01
Authorization: Bearer {{bearerToken}}
Content-Type: application/cloudevents+json

{
    "specversion": "1.0",
    "id": "1234",
    "type": "com.ext.consumer.1.event.eventcreated",
    "source": "/distribution-service",
    "subject": "/canonical/transport-movement",
    "time": "2025-05-22T13:13:19.224274698+00:00",
    "datacontenttype": "application/json",
    "data": {
        "key1": "7",
        "latitude": "38.360778548329144",
        "longitude": "-125.22284557865196"
    }
}